use_frameworks!

source 'https://github.com/iOSModularization/AHFMSpecs.git'
source 'https://github.com/CocoaPods/Specs.git'

target 'AHFMUserCenter_Example' do
  pod 'AHFMUserCenter', :path => '../'
  
  pod 'AHServiceRouter'
  
  pod 'AHFMUserCenterServices'
  pod 'AHFMUserCenterManager'
  
  pod 'AHFMDataCenter'
  pod 'AHFMNetworking'
  pod 'AHFMDataTransformers'
  
  pod 'AHFMServices'
  pod 'AHFMModuleManager'
  
  
  pod 'AHFMDownloaderManager'
  pod 'AHFMAudioPlayerManager'
  
  
  pod 'AHFMHistoryVC'
  pod 'AHFMHistoryVCManager'
  pod 'AHFMHistoryVCServices'
  
  pod 'AHFMShowPage'
  pod 'AHFMShowPageManger'
  pod 'AHFMShowPageServices'
  
  pod 'AHFMDownloadCenter'
  pod 'AHFMDownloadCenterManager'
  
  pod 'AHFMDownloadList'
  pod 'AHFMDownloadListManager'
  pod 'AHFMDownloadListServices'
  
  pod 'AHFMAudioPlayerVC'
  pod 'AHFMAudioPlayerVCManager'
  pod 'AHFMAudioPlayerVCServices'
  
  pod 'AHFMEpisodeListVC'
  pod 'AHFMEpisodeListVCManager'
  
  pod 'AHFMHistoryVC'
  pod 'AHFMHistoryVCManager'
  
  pod 'AHFMEpisodeListVC'
  pod 'AHFMAudioPlayerManager'
  
  pod 'AHFMBottomPlayer'
  pod 'AHFMBottomPlayerManager'
  pod 'AHFMBottomPlayerServices'

  target 'AHFMUserCenter_Tests' do
    inherit! :search_paths

    
  end
end
